PostgreSQL is an object-relational database management system (ORDBMS) based on POSTGRES, Version 4.2, developed at the University of California at Berkeley Computer Science Department. POSTGRES pioneered many concepts that only became available in some commercial database systems much later.

https://www.postgresql.org/docs/11/intro-whatis.html

== Download

Go to postgresql.org and Download your DB. 

For Windows develompent, I prefer to use the zip package 
installation without the need of Admin rights for development 
purpose. Unzip it into anywhere you like. 

Also I use Cygwin to execute all commands noted below.

== Setup

=== Initialize a new DB Cluster and start server

	cd postgres-10.4/pgsql/bin
	initdb -U postgres --encoding=UTF8 --pgdata=../pgdata
	pg_ctl -D ../pgdata -l ../pgdata/server.log start

This initialize a new zip installation of a PostgreSQL DB
with default 'postgres' as superuser. We will use this user
to create other users and databases. Notice that I used
explicit encoding 'UTF8'.

Login to client:

  psql -U postgres
  # List of all tables
  > \d

  # List of all databases
  > \l

  # To load sql script
  > \! pwd
  > \cd my-project
  > \i my.sql

  # Help
  > \?

  # Exit
  > \q

=== Create new users

	createuser -U postgres -P -s zemiandb

The `-P` option is used to prompt for password.
The `-s` option is to create a "superuser".

Update user password:

	psql> \password zemiandb
	-- OR use SQL command
	psql> ALTER USER zemiandb WITH PASSWORD 'zemiandb123';

Remove user password:

	psql> ALTER USER zemiandb WITH PASSWORD '';

Update user as superuser:

	psql> ALTER USER zemiandb WITH SUPERUSER;

Add existing user to database
	GRANT ALL ON DATABASE mydb TO zemiandb;

Change database owner
	ALTER DATABASE zemiandb OWNER TO mydb;

=== Create new database

	createdb -U postgres -O zemiandb zemiandb

Create a new database and assign 'zemiandb' as owner.

We can now login into this new DB:

	psql -U zemiandb zemiandb

You can drop the DB and recreate again

	dropdb -U postgres zemiandb

== Sample Tables

	psql -U zemiandb zemiandb < samples/test.sql

== Create a DB dump file and restore DB

	pg_dump -U postgres zemiandb > ../zemiandb.dump
	psql -U postgres zemiandb2 < ../zemiandb.dump

== Setup Sample DB

See https://wiki.postgresql.org/wiki/Sample_Databases

We will create one database `samples` and then create
separate schema for each DB sample added below:

	createdb -U zemiandb -O zemiandb samples
	psql -U zemiandb samples

=== The `world` DB

----
psql> CREATE SCHEMA world;
psql> SET SCHEMA 'world';
psql> \i samples/world.sql
----

=== The `pagila` DB

Pagila: Based on MySQL's replacement for World, Sakila, which is itself inspired by the Dell DVD Store. 

NOTE: The pagila dump file already set schema to "public". We will load it there
then rename it into "pagila"

----
psql> \i samples/pagila-schema.sql
psql> \i samples/pagila-data.sql
psql> ALTER SCHEMA public RENAME TO pagila;
psql> CREATE SCHEMA public;
----

=== The `employees` DB

See https://github.com/vrajmohan/pgsql-sample-data/tree/master/employee

== Database Cluster

A database cluster is a collection of databases that is managed by a single instance of a running database server. After initialization, a database cluster will contain a database named postgres, which is meant as a default database for use by utilities, users and third party applications. 

  $ initdb -D /usr/local/pgsql/data

See https://www.postgresql.org/docs/current/creating-cluster.html

== Some Java Libraries and Tools that work with Data

* Java JDBC https://docs.oracle.com/javase/tutorial/jdbc/basics/index.html
* Spring Data Access https://docs.spring.io/spring/docs/current/spring-framework-reference/data-access.html#jdbc-choose-style
* Java EE code generator https://jeddict.github.io
* Java DSL to SQL http://www.jooq.org
* Java Persistent Framework that's SQL friendly http://www.mybatis.org/mybatis-3/
* Java Persistent Framework that's HQL friendly (ORM) http://hibernate.org/
