PostgreSQL is an object-relational database management system (ORDBMS) based on POSTGRES, Version 4.2, developed at the University of California at Berkeley Computer Science Department. POSTGRES pioneered many concepts that only became available in some commercial database systems much later.

https://www.postgresql.org/docs/11/intro-whatis.html

== Download

Go to postgresql.org and Download your DB. 

For Windows develompent, I prefer to use the zip package 
installation without the need of Admin rights for development 
purpose. Unzip it into anywhere you like. 

Also I use Cygwin to execute all commands noted below.

== Setup

=== Initialize a new DB Cluster and start server

	cd postgres-10.4/pgsql/bin
	initdb -U postgres --encoding=UTF8 --pgdata=../pgdata
	pg_ctl -D ../pgdata -l ../pgdata/server.log start

This initialize a new zip installation of a PostgreSQL DB
with default 'postgres' as superuser. We will use this user
to create other users and databases. Notice that I used
explicit encoding 'UTF8'.

Login to client:

  psql -U postgres
  # List of all tables
  > \d

  # List of all databases
  > \l

  # Help
  > \?

  # Exit
  > \q

=== Create new users

	createuser -U postgres -P zemiandb

The `-P` option is used to prompt for password.

To update user password:

	psql> \password zemiandb
	-- OR use SQL command
	psql> ALTER USER zemiandb WITH PASSWORD 'zemiandb123';

Or to remove user password:

	psql> ALTER USER zemiandb WITH PASSWORD '';


=== Create new database

	createdb -U postgres -O zemiandb zemiandb

Create a new database and assign 'zemiandb' as owner.
We can now login into this new DB:

	psql -U zemiandb zemiandb

* You can drop the DB and recreate again

	dropdb -U postgres zemiandb

== Sample Tables

  psql -U zemiandb zemiandb < samples/test.sql

== Add a new user to database

	-- Add new user to database
	GRANT ALL ON DATABASE mydb TO zemiandb

	-- Change database owner
	ALTER DATABASE zemiandb OWNER TO mydb

== Create a DB dump file and restore DB

	pg_dump -U postgres zemiandb > ../zemiandb.dump
	psql -U postgres zemiandb2 < ../zemiandb.dump

== Setup `pagila` Example DB

----
createuser -U postgres pagila
createdb -U postgres -O pagila pagila
psql -U pagila pagila < pagila-schema.sql
psql -U pagila pagila < pagila-data.sql
----